# -*- coding: utf-8 -*-
"""Wrangling-Viz in Python - S7 - example code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q31xq2iAVT2XBSCWOSLOvXnNPlwR7EiH

# Data Wrangling and Visualization in Python

## 1. LOAD PACKAGES
"""

import pandas as pd # Dot data manipulation
import seaborn as sns # For visualization
import matplotlib.pyplot as plt  # For visualization

"""## 2. LOAD AND EXPLORE DATA"""

# A. Load iris dataset from seaborn package
iris = sns.load_dataset('iris')

# Get the name of the variables
print(iris.columns)

# Examine the object type, DataFrame
type(iris)

# A. Load iris dataset from a GitHub repo

# URL to the raw CSV file
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"

# Read the CSV directly from the web
df = pd.read_csv(url)

type(df)

# Display the first few rows
df.head()

# Get statistical summary of all numerical variables
df.describe()

"""## 3: DATA WRANGLING"""

# --- Example 3a: Create new variables, filter, and sort
iris.assign(sepal_area = df['sepal_length'] * df['sepal_width'] ).query('sepal_length > 5').sort_values(by = 'sepal_area', ascending=False)

# Example 3b: Summarise data by groups
iris_mean = iris.groupby('species')['petal_length'].agg(['count', 'mean', 'median']).reset_index()

iris_mean

"""## 4: VISUALIZATION"""

# Set theme of graphs
sns.set_theme(style = 'whitegrid')

# 4a: Bar Chart
plt.figure(figsize=(8,6))
sns.barplot(data = iris_mean, x = 'species', y = "mean")
plt.title('Average Petal Length by Species')
plt.ylabel('Mean Length (cm)')
plt.show()

# 4b: Histogram
sns.histplot(data=iris, x='sepal_width', bins=15, kde=True, color='steelblue')

# 4c: Scatter Plot with Linear Regression

scatter_plot = sns.lmplot(
    data=iris,
    x='sepal_length',
    y='sepal_width',
    hue = 'species'
)

# 4d: Scatter Plot with Linear Regression
scatter_plot = sns.lmplot(
    data=iris,
    x='sepal_length',
    y='sepal_width',
    hue='species',    # This is like aes(color = Species)
    height=6,
    aspect=1.2,
    ci=None           # Equivalent to se=FALSE in ggplot
)
plt.title('Sepal Length vs. Width with Regression Lines')
plt.show()

plt.show()

"""# 5: EXPORTING FIGURES"""

scatter_plot.savefig("iris_scatterplot.png")

